import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Modal from "../components/Modal";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="h-screen scrollbar-hide sm:scrollbar-default overflow-y-scroll scrollbar scrollbar-thumb-gray-300 bg-[#fafafa]">
      {/* Modal */}
      <Modal />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Feed */}
      <Feed />
    </div>
  );
}
